server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1701x?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
        name: p2p_JWT # 应用名称
  redis:
    host: 127.0.0.1
    password:
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bw.entity
  configuration:
    map-underscore-to-camel-case: true  #字段实体属性映射驼峰转换s
logging:
  level:
    com.zhangzhipeng.dao: debug  #sql日志打印
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true